### ISSUE TITLE
Unable to install bundletool with Yarn on my M1 Mac

### ISSUE THREAD

**Issue by mikefisher84** [Ribeiro-Tiago/bundletool#11]
Hi guys I have a project that uses bundle tool as a dependency. It installs fine on intel Macs but when I try to install it on my M1 Mac with Yarn 1.22 and Node 16 I get an error every time. What's odd is it seems to install ok when using NPM regardless of the processor architecture. However our project doesn't use NPM. 

Here's the error:

```
error /Users/dev/myapp/node_modules/bundletool: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/dev/myapp/node_modules/bundletool
Output:
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:1172:7)
    at getCachedBinary (/Users/dev/myapp/node_modules/bundletool/install.js:90:26)
    at setupBundletool (/Users/dev/myapp/node_modules/bundletool/install.js:111:22)
    at Object.<anonymous> (/Users/dev/myapp/node_modules/bundletool/install.js:128:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_INVALID_ARG_TYPE'
```

**Comment by Ribeiro-Tiago** [comment]
Turns out yarn doesn't specify an env variable for its caching directory. It's already fixed in dev branch will work on fixing the other open issue so I can push a new release with both fixes
