### ISSUE TITLE
Unable to install Bundletool 1.1.5 with Yarn 1.22

### ISSUE THREAD

**Issue by mikefisher84** [Ribeiro-Tiago/bundletool#14]
Hey guys thanks for releasing the new 1.1.5 version with the Yarn fix. However when trying to install the new version I'm still getting errors although they seem different. 

Now when I try to install 1.1.5 I get this error

```
error /Users/mike/dev/myapp/node_modules/bundletool: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/mike/dev/myapp/node_modules/bundletool
Output:
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './helpers/bind'
Require stack:
- /Users/mike/dev/myapp/node_modules/axios/lib/utils.js
- /Users/mike/dev/myapp/node_modules/axios/lib/axios.js
- /Users/mike/dev/myapp/node_modules/axios/index.js
- /Users/mike/dev/myapp/node_modules/bundletool/install.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/mike/dev/myapp/node_modules/axios/lib/utils.js:3:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mike/dev/myapp/node_modules/axios/lib/utils.js',
    '/Users/mike/dev/myapp/node_modules/axios/lib/axios.js',
    '/Users/mike/dev/myapp/node_modules/axios/index.js',

```

This happens using Yarn 1.22.17 on an M1 Mac running Monterey. 

For reference the pre 1.1.5 error was this: 

```
error /Users/mike/app/node_modules/bundletool: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/mike/app/node_modules/bundletool
Output:
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:1172:7)
    at getCachedBinary (/Users/mike/app/node_modules/bundletool/install.js:90:26)
    at setupBundletool (/Users/mike/app/node_modules/bundletool/install.js:111:22)
    at Object.<anonymous> (/Users/mike/app/node_modules/bundletool/install.js:128:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

Any idea how I can resolve this?

**Comment by Ribeiro-Tiago** [comment]
huh.. there seems that axios didn't get installed. What are dependencies do you have on your project? Have you tried reinstalling node_modules (`rm -rf node_modules && yarn` - assuming you now have bundletool defined as a dependency on your package.json)
